# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='domicio',
            new_name='domicilio',
        ),
    ]
